itssupp/urls.py
from django.urls import path

from . import views
app_name = 'itssupp'


urlpatterns = [
    path('', views.index, name='index'),
    path('abandonPage', views.abandonPage, name='abandonPage'),
    path('info/', views.info),

]

mysite3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('itssupp/', include('itssupp.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views
app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

itssupp/models.py
import datetime

from django.db import models
from django.utils import timezone

class Testing():

    test_text = "this is my test"

    def doSomething(self):
        return (self.test_text)














#this stuff gets data from database (from tutorial)
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

itssupp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404,render
from django.template import loader
from django.urls import reverse
from .models import Choice, Question, Testing
from itssupp.Support_abandonFDorSPandChildren import Support_abandonFDorSPandChildren


def index(request):
    #template = loader.get_template('itssupp/index.html')
    return render(request, 'itssupp/index.html')



def abandonPage(request):
  return render(request, 'itssupp/abandonPage.html')


# this gets all the data from the input form and sends to abandonSPreport.html
def info(request):
    mySupportTask = Support_abandonFDorSPandChildren()
    form = request.GET   # get the input from the form on the page
    servername = form['server']
    ticketnum = form['ticketnum']
    function = form['function']
    spOrFd = form['SpsOrFds']

    mySupportTask.doAbandon(servername, ticketnum, function, spOrFd)
    NumErrors = str(mySupportTask.errorCnt)
    taskServer = mySupportTask.server
    taskDBcomment = mySupportTask.sComment
    taskFunction = mySupportTask.functionText
    sampleSet = mySupportTask.sampleSet
    sowSet = mySupportTask.sowSet
    spSet = mySupportTask.spSet
    confirmQuery = mySupportTask.confirmQuery
    workflowURL = mySupportTask.route2workflowURL
    taskServerName = mySupportTask.servername

    if (function == "SPchildren" or function == "SPchildrenTest"):
        return render(request, 'itssupp/abandonSPreport.html', {'server': taskServer,
                                                         'comment':taskDBcomment,
                                                         'function':taskFunction,
                                                         'samples':sampleSet,
                                                         'sows':sowSet,
                                                         'sps':spSet,
                                                         'query':confirmQuery,
                                                         'url': workflowURL,
                                                         'jiraTicket':ticketnum,
                                                         'serverName': taskServerName})
    else :   # (function == "FDchildren" or function == "FDchildrenTest"):
        apSet = mySupportTask.apSet
        atSet = mySupportTask.atSet
        fdSet = mySupportTask.fdSet
        return render(request, 'itssupp/abandonFDreport.html', {'server': taskServer,
                                                         'comment':taskDBcomment,
                                                         'function':taskFunction,
                                                         'samples':sampleSet,
                                                         'sows':sowSet,
                                                         'sps':spSet,
                                                         'aps': apSet,
                                                         'ats': atSet,
                                                         'fds': fdSet,
                                                         'query':confirmQuery,
                                                         'url': workflowURL,
                                                         'jiraTicket':ticketnum,
                                                         'serverName': taskServerName})

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404,render
from django.template import loader
from django.urls import reverse
from .models import Choice, Question

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list}

    #use shortcut render
    return render(request, 'polls/index.html', context)
    #return HttpResponse(template.render(context, request))


#use shortcut below
#def detail(request, question_id):
#    return HttpResponse("You're looking at question %s." % question_id)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})



def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

itssupp/templates/itssupp/abandonFDreport.html
<!DOCTYPE html>
<html>
<body>
function: {{function}}
<h1>Abandoned FD and Children Report <br>On {{serverName}}, for ITSSUPP - {{jiraTicket}}</h1>

<h4>The statuses of the following entities  were changed to abandoned/cancelled:</h4>
Samples: <p id="sam">{{ samples }}</p>
Sows: <p id="sows">{{ sows }}</p>
SPs: <p id="sps">{{ sps }}</p>
Analysis Projects: <p id="aps">{{ aps }}</p>
Analysis Tasks: <p id="ats">{{ ats }}</p>
FDs: <p id="fds">{{ fds }}</p>

<h2> Use this query to confirm the statuses: </h2>
{{ query }}

<h4 >  Use this set of samples with routeToWorkflow controller to remove any samples from queues: </h4>

<p id="demo"></p>
<script>
 {
    var s = document.getElementById("sam").innerHTML;
    var sliceStr = s.slice(2,s.length-2);
    const splitStr = sliceStr.split("', '")
    var text = ""

    for (i = 0; i < splitStr.length; i++) {
    text += splitStr[i] + "<br>";
        }
     document.getElementById("demo").innerHTML = text;
}
</script>

Route to workFlow URL:  <a id="urlid">{{ url }}</a>

<p id="demo2"></p>
<script>
 {
    var urltext = document.getElementById("urlid").innerHTML;
    document.write("<p>Link: " + urltext.link(urltext) + "</p>");
}
</script>
</body>
</html>

itssupp/templates/itssupp/abandonPage.html
<h1>Abandon FDs (or SPs ) and Children</h1>

<cr></cr>
<form action="/itssupp/info/" method ="get">
  Environment:<br>
  <input type="radio" name="server" value="Prod"> Production(Clarity-prd01)<br>
  <input type="radio" name="server" value="Int"> Integration (Clarity-int01)<br>
  <input type="radio" name="server" value="Dev"> Development (Clarity-dev01)<br>
  <br><br>

  ITSSUPP ticket number:
  <input type="text" name="ticketnum", size="4">
  <br><br>
  Choose Function:
  <br>
  <input type="radio" name="function" value="FDchildren"> Abandon FD and Children (FD,AP,AT,SP,Samples and SOWs)<br>
  <input type="radio" name="function" value="SPchildren"> Abandon SP and Children (SP,Samples and SOWs)<br>
  <input type="radio" name="function" value="FDchildrenTest">Test: Abandon FD and Children (no database updates)<br>
  <input type="radio" name="function" value="SPchildrenTest">Test: Abandon SP and Children (no database updates)<br>
  <br><br>
  What are the FDs (or SPs)? (separate by comma):
  <br>
  <input type="text" name="SpsOrFds" size="80">
  <br><br>

  <input type="submit" value="Submit">
  <input type="reset">
</form>

itssupp/templates/itssupp/abandonSPreport.html
<!DOCTYPE html>
<html>
<body>
function: {{function}}
<h1>Abandoned SP and Children Report <br>On {{serverName}}, for ITSSUPP - {{jiraTicket}}</h1>

<h4>The statuses of the following entities  were changed to abandoned:</h4>
Samples: <p id="sam">{{ samples }}</p>
Sows: <p id="sows">{{ sows }}</p>
SPs: <p id="sps">{{ sps }}</p>

<h2> Use this query to confirm the statuses: </h2>
{{ query }}

<h4 >  Use this set of samples with routeToWorkflow controller to remove any samples from queues: </h4>

<p id="demo"></p>
<script>
 {
    var s = document.getElementById("sam").innerHTML;
    var sliceStr = s.slice(2,s.length-2);
    const splitStr = sliceStr.split("', '")
    var text = ""

    for (i = 0; i < splitStr.length; i++) {
    text += splitStr[i] + "<br>";
        }
     document.getElementById("demo").innerHTML = text;
}
</script>

Route to workFlow URL:  <a id="urlid">{{ url }}</a>

<p id="demo2"></p>
<script>
 {
    var urltext = document.getElementById("urlid").innerHTML;
    document.write("<p>Link: " + urltext.link(urltext) + "</p>");
}
</script>
</body>
</html>

itssupp/templates/itssupp/confirmation_dontuse.html
<!DOCTYPE html>
<html>
<body>
<h1>Abandoned SP and Children Report</h1>
<br><br>

The ojbect values are:
<br>
<br> Server: {{ server }}
<br> Comment for DB: {{ comment }}
<br>Function to do:  {{ function }}
<br>
<br>Samples: <p id="sam">{{ samples }}</p>
<br>
<br>Sows:  {{ sows }}
<br>
<br>SPs:  {{ sps }}
<br><br>
<h2> Use this query to confirm the statuses: </h2>
{{ query }}

<p id="demo">Click the button to change the text in this paragraph.</p>
<button onclick="myFunction()">Try it</button>

<script>
function myFunction() {
    var s = document.getElementById("sam").innerHTML;
    var sliceStr = s.slice(2,s.length-2);
    const splitStr = sliceStr.split("', '")
    var text = ""

    for (i = 0; i < splitStr.length; i++) {
    text += splitStr[i] + "<br>";
        }
     document.getElementById("demo").innerHTML = text;
}
</script>

</body>
</html>

itssupp/templates/itssupp/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

itssupp/templates/itssupp/index.html
<style>
body {background-color: powderblue;}
li{color: green;  }
li a { color: red;  }
</style>

<h1>ITS Support tools</h1>
 <ul>
 <li><a href=abandonPage>Abandon FD/SP</a></li>
 <li>Change PM</li>
</ul>

itssupp/templates/itssupp/results.html
<h1>Hi There</h1>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
<style>
li{color: green;  }
li a { color: red;  }
</style>

ITS Support tools
 <ul>
 <li>Abandon FD/SP</li>
 <li>Change PM</li>
</ul>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>